name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name : Authentication Docker Hub
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Logging in to Docker Hub"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Logged in to Docker Hub."

    - name: Build Docker Image
      run : |
        docker build -t gerodron/graphsql .
        docker build -t gerodron/graphsql:0.0.4 .
        
    - name: Push Docker Image
      run : |
        docker push gerodron/graphsql
        docker push gerodron/graphsql:0.0.4

    
      
      
