name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Determine database version
        id: image-version
        uses: paulhatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: Authenticate with Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          NEW_VERSION: ${{steps.image-version.outputs.version}}
        run: |
          echo "Logging in to Docker Hub"
          docker login -u ${{ env.DOCKER_USER }} -p ${{ env.DOCKER_PASSWORD }}
          echo "New version: $NEW_VERSION"
          echo "Logged in to Docker Hub."

      # - name: Build Docker image
      #   run: |
      #     docker build -t gerodron/graphsql .
      #     docker build -t gerodron/graphsql:0.0.4 .

      # - name: Push Docker image
      #   run: |
      #     docker push gerodron/graphsql
      #     docker push gerodron/graphsql:0.0.4
